ProjectManagementTool/Models/OverViewModel.cs
using ProjectManagementTool.PMTWebService;
using System.Linq;
using System.Security.Claims;
using System.Threading;
using System.Threading.Tasks;

namespace ProjectManagementTool.Models
{
    public class OverViewModel
    {
        public static async Task<OverviewDetails> GetOvervieDetails(int CompanyId)
        {
            var identity = (ClaimsPrincipal)Thread.CurrentPrincipal;
            string sid = identity.Claims.SingleOrDefault(x => x.Type == ClaimTypes.PrimarySid).Value;

            OverviewDetails od = new OverviewDetails();
            using (var client = new PGMTWebServiceClient())
            {
                od = await client.GetOverViewAsync(CompanyId, int.Parse(sid));
            }
            return od;
        }

    }
}

ProjectManagementTool/Models/ViewModels/ProjectViewModel.cs
using ProjectManagementTool.Models.ViewModels;
using ProjectManagementTool.PMTWebService;
using System.Collections.Generic;

namespace ProjectManagementTool.Models
{
    public class ProjectViewModel
    {

        private ProjectModel _projectModel;
        
        public ProjectModel ProjectModel
        {
            get
            {
                if (_projectModel == null)
                    _projectModel = new ProjectModel();
                return _projectModel;
            }
        }


    }
}

ProjectManagementTool/Controllers/DataController.cs
using ProjectManagementTool.Models;
using ProjectManagementTool.PMTWebService;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using System;

namespace ProjectManagementTool.Controllers
{
    public class DataController : Controller
    {
       // public new HttpRequest Request = HttpContext.Current.Request;

        // POST: Data/Create
        public JsonResult Create(FormCollection collection)
        {
            try
            {
                UserProfile profile = new UserProfile();
                if (Request.IsAuthenticated)
                {

                    if (User.IsInRole(UserRoles.ADMIN) || User.IsInRole(UserRoles.MANAGER) || User.IsInRole(UserRoles.IT))
                    {
                        using (var client = new PGMTWebServiceClient())
                        {

                            profile = client.CreateUserProfile(collection["UserInfo." + nameof(UserInfo.UserName)], collection["UserInfo." + nameof(UserInfo.password)], collection["UserInfo." + nameof(UserInfo.emailaddress)], collection["UserInfo." + nameof(UserInfo.FirstName)], collection["UserInfo." + nameof(UserInfo.LastName)]);
                            if (profile != null)
                            {
                                return Json(profile);
                            }
                        }
                    }
                    else
                    {
                        profile.HasMessage = true;
                        profile.Message = "You are not authorize to create User Profile";
                    }

                }
                ///TempData["profile"] = Profile;
                return Json("");
            }
            catch (Exception ex)
            {
                return Json("");
            }
        }

        public async Task<JsonResult> GetUsers(int userId = 0)
        {
            List<Users> userCollection = new List<Users>();
            using (var client = new PGMTWebServiceClient())
            {
                Users[] users = await client.GetUsersAsync();
                userCollection = users.ToList();
                if (userId > 0)
                {
                    return Json(userCollection.SingleOrDefault(x => x.ID.Equals(userId)), JsonRequestBehavior.AllowGet);
                }
            }

            return Json(userCollection, JsonRequestBehavior.AllowGet);
        }

        public JsonResult EditUser(FormCollection collection)
        {
            try
            {
                if (Request.IsAuthenticated)
                {
                    bool result = false;
                    if (User.IsInRole(UserRoles.ADMIN) || User.IsInRole(UserRoles.MANAGER) || User.IsInRole(UserRoles.IT))
                    {
                        using (var client = new PGMTWebServiceClient())
                        {
                            Users usr = new Users()
                            {
                                ID = int.Parse(collection["user_id"]),
                                Active = true,
                                Email = collection[nameof(UserInfo.emailaddress)],
                                FirstName = collection[ nameof(UserInfo.FirstName)],
                                LastName = collection[ nameof(UserInfo.LastName)],
                                //Status = StatusEnum._ACTIVE_,
                                Password = collection[ nameof(UserInfo.password)],
                                //UserProfile = "",
                                //UserProfileID = "",
                                UserName = collection[ nameof(UserInfo.UserName)],
                                //UserRole = null,
                                //UserRoleId = null,

                            };
                            result = client.UpdateUser(usr);
                            if (result)
                            {
                                return Json(result);
                            }
                        }
                    }


                }

            }
            catch(Exception ex)
            {
             //   return Content(HttpStatusCode.BadRequest, ex.Message);
            }
            return Json("");
        }

        //// POST: Data/Edit/5
        //public IHttpActionResult Edit(int id, FormCollection collection)
        //{
        //    return Ok();
        //}


        //// GET: Data/Delete/5
        //public IHttpActionResult Delete(int id)
        //{
        //    return Ok();
        //}

        //// POST: Data/Delete/5

        //public IHttpActionResult Delete(int id, FormCollection collection)
        //{
        //    return Ok();
        //}
    }
}

ProjectManagementTool/Controllers/PGMToolController.cs
using ProjectManagementTool.Models;
using ProjectManagementTool.PMTWebService;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Http.Cors;
using System.Web.Mvc;
using System.Web.Routing;

namespace ProjectManagementTool.Controllers
{
    [Authorize, EnableCors(origins: "*", headers: "*", methods: "*")]
    public class PGMToolController : Controller
    {

        private ProjectModel projectModel;
        // GET: PGMTool
        public PGMToolController()
        {

            if (projectModel == null)
                projectModel = new ProjectModel();
        }
        public ActionResult Manage()
        {

            return View();
        }

        //Project Views
        public ActionResult Projects(string p = "0")
        {
            if (p.Equals("0"))
            {
                return RedirectToAction("OverView");
            }
            return PartialView("_PGMProjectList");
        }

        public async Task<ActionResult> ProjectDetails(int cmp, int PrjId)
        {
            LoadLeftSideMenu();
            if (PrjId > 0)
            {
                ProjectDetailsModel model = new ProjectDetailsModel(Request);
                projectModel.Project = await model.GetProjectstAsync(cmp, PrjId);

                if (projectModel.Project != null && projectModel.Project.CommentList.Length > 0)
                {
                    StringBuilder builder = new StringBuilder();
                    foreach (var comment in projectModel.Project.CommentList)
                    { //<p>@comment.Time_Stamp (@Model.ProjectModel.GetUserName((int)@comment.UpdatedByUserID)): <blockquote>@comment.Comment</blockquote></p>
                        builder.AppendFormat("<p>{0} ({1}): <blockquote>{2}</blockquote></p>", comment.Time_Stamp, projectModel.GetUserName(comment.UpdatedByUserID), comment.Comment);
                        builder.AppendLine(@"<hr class='fa-flip - horizontal' />");
                    }
                    projectModel.Comments = new Comments();
                    projectModel.Comments.Comment = MvcHtmlString.Create(builder.ToString()).ToString();
                }

            };

            return View(projectModel);
        }
        //Overview
        public async Task<ActionResult> OverView(string partial)
        {
            LoadLeftSideMenu();
            projectModel.OverviewDetails = await OverViewModel.GetOvervieDetails((Request["cmp"] != null) ? int.Parse(Request["cmp"]) : 0);
            return View(projectModel);
        }

        public ActionResult ManageUsers()
        {
            return View(projectModel);
        }

        public ActionResult Details()
        {
            LoadLeftSideMenu();
            ProjectDetailsModel model = new ProjectDetailsModel(Request);
            projectModel.Projects = Task.Run(() => model.GetProjectsListAsync()).Result;
            return View(projectModel);
        }

        public ActionResult CreateNewProject(string cmp)
        {
            LoadLeftSideMenu();
            projectModel.Project = new PMTWebService.Projects
            {
                CompanyID = int.Parse(cmp)
            };

            return View(projectModel);
        }

        public async Task<ActionResult> EditProject(int cmp, int PrjId, bool EditPrj)
        {
            LoadLeftSideMenu();
            if (PrjId > 0)
            {
                ProjectDetailsModel model = new ProjectDetailsModel(Request);
                projectModel.Project = await model.GetProjectstAsync(cmp, PrjId);
                ViewBag.Editproject = true;
            };

            return RedirectToAction("ProjectDetails", new RouteValueDictionary(new { Controller = "PGMTool", action = "ProjectDetails", cmp = cmp, PrjID = PrjId, Editproject = true }));
        }

        public async Task<ActionResult> CancelEditProject(int cmp, int PrjId)
        {
            LoadLeftSideMenu();
            if (PrjId > 0)
            {
                ProjectDetailsModel model = new ProjectDetailsModel(Request);
                projectModel.Project = await model.GetProjectstAsync(cmp, PrjId);
                ViewBag.Editproject = false;
                Session.Abandon();
            };

            return RedirectToAction("ProjectDetails", new RouteValueDictionary(new { Controller = "PGMTool", action = "ProjectDetails", cmp = cmp, PrjID = PrjId }));
        }

        public ActionResult PrintProject(int cmp, int PrjId)
        {
            ProcessStartInfo psi = new ProcessStartInfo
            {
                Verb = "print",
                FileName = Request.RawUrl,
                RedirectStandardOutput = false,
                WindowStyle = ProcessWindowStyle.Hidden,
                UseShellExecute = true
            };
            Process p = new Process
            {
                StartInfo = psi
            };
            p.Start();
            p.WaitForInputIdle();
            Thread.Sleep(3000);
            if (p.CloseMainWindow() == false)
            {
                p.Kill();
            }
            return PartialView("_PrintView", projectModel);
        }

        [HttpPost]
        public ActionResult CreateProject(FormCollection form, ProjectModel projectModel, int cmp)
        {
            LoadLeftSideMenu();
            var identity = (ClaimsPrincipal)Thread.CurrentPrincipal;
            string sid = identity.Claims.SingleOrDefault(x => x.Type == ClaimTypes.PrimarySid).Value;
            int userId = default(int);
            int projectId = default(int);
            try
            {
                if (int.TryParse(sid, out userId))
                {
                    using (var client = new PMTWebService.PGMTWebServiceClient())
                    {
                        Projects project = new Projects();
                        ProjectModel model = new ProjectModel();
                        project.ProjectName = projectModel.Project.ProjectName;
                        #region comments

                        List<Comments> comments = new List<Comments>();

                        comments.Add(new Comments()
                        {
                            Comment = projectModel.Comments.Comment,
                            UpdatedByUserID = int.Parse(sid),
                            Time_Stamp = DateTime.Now
                        });
                        project.CommentList = comments.ToArray();

                        #endregion

                        project.StartDate = projectModel.Project.StartDate;
                        project.EstimatedCompletionDate = projectModel.Project.EstimatedCompletionDate;
                        project.Status = projectModel.Project.Status;
                        project.ProjectScope = projectModel.Project.ProjectScope;
                        project.StreetNumber = projectModel.Project.StreetNumber;
                        project.StreetAddress = projectModel.Project.StreetAddress;
                        project.City = projectModel.Project.City;
                        project.State = projectModel.Project.State;
                        project.ZipCode = projectModel.Project.ZipCode;
                        project.Lot = projectModel.Project.Lot;
                        project.Zone = projectModel.Project.Zone;
                        project.CompanyID = cmp;
                        project.UpdatedByUserID = int.Parse(sid);
                        project.CreatedDate = DateTime.Now;
                        project.IsDeleted = false;


                        List<MaterialList> materialList = new List<MaterialList>();
                        foreach (var material in projectModel.MaterialList)
                        {
                            materialList.Add(material);
                            project.MaterialList = materialList.ToArray();
                        };

                        ProjectResponse response = client.AddProject(int.Parse(sid), project);

                        if (response.Success)
                        {
                            projectId = response.ProjectID;
                            foreach (var attachment in projectModel.Attachments)
                            {
                                attachment.ProjectID = projectId;
                                client.AddAttachments(userId, attachment);
                            };
                        }

                        Session["MaterialList"] = null;
                        Session["Attachments"] = null;
                    }
                }

            }
            catch (Exception ex)
            {
                //throw;
            }


            return RedirectToAction("ProjectDetails", new RouteValueDictionary(new { Controller = "PGMTool", action = "ProjectDetails", cmp = form["CompanyId"], PrjID = projectId }));
        }

        [HttpPost]
        public async Task<ActionResult> ProjectUpdate(FormCollection form, ProjectModel projectModel, int cmp, int PrjID)
        {

            LoadLeftSideMenu();
            var identity = (ClaimsPrincipal)Thread.CurrentPrincipal;
            string sid = identity.Claims.SingleOrDefault(x => x.Type == ClaimTypes.PrimarySid).Value;
            int userId = default(int);
            int projectId = PrjID;
            try
            {
                if (int.TryParse(sid, out userId))
                {
                    using (var client = new PMTWebService.PGMTWebServiceClient())
                    {
                        Projects project = new Projects
                        {
                            ID = PrjID,
                            CompanyID = cmp,
                            ProjectName = projectModel.Project.ProjectName
                        };
                        #region comments

ProjectManagementTool/Views/PGMTool/Details.cshtml
@model ProjectManagementTool.Models.ProjectModel

@{
    ViewBag.Title = "My Projects Details";
    Layout = "~/Views/Shared/_PMGTFrameLayout.cshtml";
}

<section class="container-fluid">
    <div class="row">
        <div class="col-12">
            <h2>@ViewBag.Title</h2>

            <p>
                @Html.ActionLink("Create New", "CreateNewProject", new { cmp=Request["cmp"]})
            </p>
        </div>
    </div>
</section>

<section class="container-fluid">
    
    <div class="table-responsive col-xs-4 col-xs-12">

        <table class="table" id="TableData">
            <thead>
                <tr>
                    <th scope="col">Project Id</th>
                    <th scope="col">Project Name</th>
                    <th scope="col">Project Status</th>
                    <th scope="col">Modified Date</th>
                    <th scope="col">Started Date</th>
                </tr>
            </thead>

            <tbody>
                @if (Model.Projects != null && Model.Projects.Count > 0)
                    {
                        foreach (var proj in Model.Projects)
                        {
                    <tr>
                        <td scope="row">
                            @proj.ID
                        </td>
                        <td>
                            <a href="ProjectDetails?cmp=@Request["cmp"]&PrjId=@proj.ID"> @proj.ProjectName</a>
                        </td>
                        <td>
                            @proj.Status
                        </td>
                        <td>
                            @proj.ModifiedDate.Value.ToShortDateString()
                        </td>
                        <td>
                            @proj.StartDate.Value.ToShortDateString()
                        </td>
                    </tr>

                        }
                    }
            </tbody>

        </table>

    </div>

</section>

@section scripts{
    <script>
        $('#TableData').DataTable({
            'paging': true,
            'ordering': true,
            'info': true
        });
    </script>
}

ProjectManagementTool/Views/PGMTool/PrintProject.cshtml
@model ProjectManagementTool.Models.ProjectModel
@{
    Layout = "~/Views/Shared/_PMGTFrameLayout.cshtml";
}

@{Html.RenderPartial("_PrintView", Model)};

ProjectManagementTool/Views/PGMTool/Projects.cshtml
@model ProjectManagementTool.Models.ViewModels.PGMToolVM
@{
    Layout = "~/Views/Shared/_PMGTFrameLayout.cshtml";
}
<div class="grid-y medium-grid-frame">

    <div class="cell medium-auto medium-cell-block-container">
        <div class="grid-x grid-padding-x grid-padding-x ">

            <div id="ProjectSection" class="small-12 columns callout large-flex-child-auto border-none">

                @{Html.RenderPartial("_ProjectDetailsView", Model);}
            </div>
        </div>

    </div>


</div>

ProjectManagementTool/Views/PGMTool/_DetailAttachmentView.cshtml
@model ProjectManagementTool.Models.ProjectModel

<table class="table ">
    <thead>
        <tr>
            <th style="width:120px">File</th>
            <th>ID</th>
            <th>File Name</th>
            <th style="width:50%">Description</th>
            <th>Created Date</th>
            
        </tr>
    </thead>
    <tbody>

        @if (Model.ProjectModel.Project != null && Model.Project.AttachmentList.Length > 0)
        {
            foreach (var attachment in Model.Project.AttachmentList)
            {
                <tr>
                    <td>
                        <a href="/PGMTImageHandler.ashx?PictureId=@attachment.ID&thumbnail=false"  data-lightbox="attachments" data-title="@attachment.Description">
                            <img src="/PGMTImageHandler.ashx?PictureId=@attachment.ID&thumbnail=true&thumbNailSize=120" width="120" height="120" class="rounded img-fluid" />
                        </a>
                    </td>
                    <td>@attachment.ID </td>
                    <td>@attachment.FileName </td>
                    <td>@attachment.Description </td>
                    <td>@attachment.CreatedDate </td>
                </tr>
            }
        }
    </tbody>
</table>

ProjectManagementTool/Views/PGMTool/_DetailCommentView.cshtml
@model ProjectManagementTool.Models.ProjectModel
@*@if (Model.ProjectModel.Project != null && Model.ProjectModel.Project.CommentList.Length > 0)
    {
        foreach (var comment in Model.ProjectModel.Project.CommentList)
        {
            <p>@comment.Time_Stamp (@Model.ProjectModel.GetUserName((int)@comment.UpdatedByUserID)): <blockquote>@comment.Comment</blockquote></p>
                <hr class="fa-flip-horizontal" />
        }
    }*@
@if (ViewBag.Editproject != null && ViewBag.Editproject == true)
{
    <div class="card col-12">
        <h4 class="card-header">Comment</h4>
        <div class="card-body">

            @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            @Html.TextAreaFor(model => model.Comments.Comment, new { @class = "form-control col-md-12" })

        </div>
    </div>
}
else
{
    <div class="card col-12">
        <h4 class="card-header">Comments History</h4>
        <div class="card-body">
            @if (Model.Comments != null)
            {
                MvcHtmlString.Create(@Model.Comments.Comment);
            }

        </div>
    </div>
}

ProjectManagementTool/Views/PGMTool/_DetailProjectView.cshtml
@model ProjectManagementTool.Models.ProjectModel
<div class="form-row">
    <div class="form-group col-md-4">
        @Html.Hidden("CompanyId", Request["cmp"])
        @Html.LabelFor(model => model.Project.ProjectName, "Project Name", htmlAttributes: new { @class = "control-label col-md-12" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Project.ProjectName, new { htmlAttributes = new { @class = "form-control", @disabled="disabled" } })
        </div>
    </div>

    <div class="form-group col-md-4">
        @Html.LabelFor(model => model.Project.StartDate, "Start Date", htmlAttributes: new { @class = "control-label date col-md-12" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Project.StartDate, new { htmlAttributes = new { @class = "form-control date datepicker", @data_Provider = "datepicker" } })
        </div>
    </div>

    <div class="form-group col-md-4">
        @Html.LabelFor(model => model.Project.EstimatedCompletionDate, "Estimated Completion Date", htmlAttributes: new { @class = "control-label col-md-12" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Project.EstimatedCompletionDate, new { htmlAttributes = new { @class = "form-control date datepicker", @data_Provider = "datepicker" } })
        </div>
    </div>


</div>

<div class="form-row">

    <div class="form-group  col-md-4">
        @Html.LabelFor(model => model.Project.Status, htmlAttributes: new { @class = "control-label col-md-12" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Project.Status, Model.SelectListForProjectStatus(), new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group col-md-4">
        @Html.LabelFor(model => model.Project.CostEstimate, "Cost Estimate", htmlAttributes: new { @class = "control-label col-md-12" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Project.CostEstimate, new { htmlAttributes = new { @class = "form-control", @data_type = "currency" } })
        </div>
    </div>

    <div class="form-group col-md-4">
        @Html.LabelFor(model => model.Project.CompanyID, htmlAttributes: new { @class = "control-label col-md-12" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Project.CompanyID, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
        </div>
    </div>

</div>
<div class="form-row">

    <div class="form-group col-12">
        @Html.LabelFor(model => model.Project.ProjectScope, "Project Scope", htmlAttributes: new { @class = "control-label col-12" })
        <div class="col-12">
            @Html.TextAreaFor(model => model.Project.ProjectScope, new { @class = "form-control col-md-12" })
        </div>
    </div>

</div>

ProjectManagementTool/Views/PGMTool/_InsertUser.cshtml
@model ProjectManagementTool.Models.ProjectModel
<h2>Profile Edit</h2>
<div class="row">

    @using (Ajax.BeginForm("Create", "Data", new AjaxOptions()
    {
        HttpMethod = "POST",
        UpdateTargetId = "insertUser",
        InsertionMode = InsertionMode.Replace,
        OnBegin = "OnBeginCallBack()",
        OnComplete = "return OnCompleteCallBack()",
        OnFailure = "return OnFailureCallBack(xhr, status, error)"
        //Confirm = "Do you want to create user profile?"
    },new { @class="container-fluid" }))
    {
        <div class="row">
            <div class="col-lg-6 col-sm-12">
                <div class="UserInformation card">
                    <div class="card-header">
                        User Information
                    </div>
                    <div class="card-body">
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="username">User Name</label>
                                @Html.TextBoxFor(Model => Model.PGMToolVM.UserInfo.UserName, "", new { @id = "username", @class = "form-control" })
                                @Html.ValidationMessageFor(Model => Model.PGMToolVM.UserInfo.UserName, string.Empty, new { @class = "error" })
                            </div>
                            <div class="form-group col-md-6">
                                <label for="lastName">Status</label>
                                <select type="text" class="form-control" id="status" name="status">
                                    <option value="true">Active</option>
                                    <option value="false">Inactive</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="firstName">First Name</label>
                                @Html.TextBoxFor(Model => Model.PGMToolVM.UserInfo.FirstName, "", new { @class = "form-control" })
                                @Html.ValidationMessageFor(Model => Model.PGMToolVM.UserInfo.FirstName)
                            </div>
                            <div class="form-group col-md-6">
                                <label for="lastName">Last Name</label>
                                @Html.TextBoxFor(Model => Model.PGMToolVM.UserInfo.LastName, "", new { @class = "form-control" })
                                @Html.ValidationMessageFor(Model => Model.PGMToolVM.UserInfo.LastName)
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="emailAddress">Email Address</label>
                                @*@Html.TextBoxFor(Model => Model.PGMToolVM.UserInfo.Email, "", new { @class = "form-control" })
                                @Html.ValidationMessageFor(Model => Model.PGMToolVM.UserInfo.Email)*@
                            </div>
                            <div class="form-group col-md-6">
                                <label for="telephone">Telephone</label>
                                @Html.TextBoxFor(Model => Model.PGMToolVM.UserInfo.Telephone, "", new { @class = "form-control" })
                                @Html.ValidationMessageFor(Model => Model.PGMToolVM.UserInfo.Telephone)
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="password">Password</label>
                                @Html.PasswordFor(Model => Model.PGMToolVM.UserInfo.password, new { @class = "form-control" })
                                @Html.ValidationMessageFor(Model => Model.PGMToolVM.UserInfo.password)
                            </div>
                            <div class="form-group col-md-6">
                                <label for="confirmPassword">Confirm Password</label>
                                @Html.PasswordFor(Model => Model.PGMToolVM.UserInfo.ConfirmPassword, new { @class = "form-control" })
                                @Html.ValidationMessageFor(Model => Model.PGMToolVM.UserInfo.ConfirmPassword)
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6 text-right">

                                <input type="submit" class="btn btn-dark" value="Save User" formnovalidate="formnovalidate" />
                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-sm-6">
                <div class="card">
                    <div class="card-header">
                        Company Information
                    </div>
                    <div class="card-body">

                    </div>
                </div>

            </div>
        </div>




    }


</div>

ProjectManagementTool/Views/PGMTool/_LeftMenuAccordion.cshtml
@model ProjectManagementTool.Models.ProjectModel
<div class="accordion md-accordion" role="tablist" id="accordionEx1" aria-multiselectable="true">
    @if (Model.Companies != null && Model.Companies.Count > 0)
    {
        foreach (var comp in Model.Companies)
        {
            <div class="card">
                <div class="card-header" id="headingOne" role="tab">

                    <a href="#collapseOne_@comp.ID" class="btn btn-link" data-toggle="collapse" data-parent="#accordionEx1" aria-expanded="false" aria-controls="collapseOne_@comp.ID">
                        <h5>  <i class="fa fa-user size-21"></i>  @comp.Name  </h5>
                    </a>

                </div>

                <div class="card-body collapse" id="collapseOne_@comp.ID" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordionEx1">
                    <ul class="nav flex-column">
                        <li class="nav-item"><a href="/PGMTool/OverView?cmp=@comp.ID" class="nav-link"><i class="fa fa-stack-overflow size-21"></i> Overview</a></li>
                        <li class="nav-item"><a href="/PGMTool/Details?cmp=@comp.ID" class="nav-link"><i class="fa fa-product-hunt size-21"></i> My Projects</a></li>
                    </ul>
                </div>

            </div>
        }
    }


</div>

ProjectManagementTool/Views/PGMTool/_ManageUsers.cshtml
<section class="container-fluid">
    <div class="row">
        <div class="col-12">
            <table class="table table-stripe display manageUserTable">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>User Name</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Email</th>
                        <th>Active</th>
                        <th>Created Date</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>

</section>

ProjectManagementTool/Views/PGMTool/_MyProjectsPartial.cshtml
<section class="container-fluid">
    
</section>